---
- hosts: all,!failed_hosts_{{ tower_workflow_job_id }}
  gather_facts: yes
  max_fail_percentage: 100
  tasks:
    - block:
        - name: Assert that free space on /var is sufficient
          assert:
            that:
              - mount.size_available > mount.size_total | float * 0.2
          vars:
              mount: "{{ (ansible_facts.mounts | selectattr('mount', 'in', '/var') | list | sort(attribute='mount')) | last }}"
      rescue:
        - name: Add host to failed inventory group
          awx.awx.tower_group:
            inventory: "{{ tower_inventory_name }}"
            name: "failed_hosts_{{ tower_workflow_job_id }}"
            hosts:
              - "{{ inventory_hostname }}"
            tower_username: "{{ tower_username }}"
            tower_password: "{{ tower_password }}"
            tower_host: "{{ tower_host }}"
            validate_certs: no
        - name: Add host to failed inventory group
          awx.awx.tower_group:
            inventory: "{{ tower_inventory_name }}"
            name: "{{ group_name }}_{{ tower_workflow_job_id }}"
            hosts:
              - "{{ inventory_hostname }}"
            tower_username: "{{ tower_username }}"
            tower_password: "{{ tower_password }}"
            tower_host: "{{ tower_host }}"
            validate_certs: no
        - fail:
            msg: "Available disk space on /var is insufficient"
